@startuml
'IMPORTANTE
'ejecutado los cambios que hice en emitir prestamohipotecario en este diagrama
'ClienteEncontrado es el cliente que se encuentra en la caja de ahorro
'CE
actor Cliente
participant "PrestamoController" as PC
participant "ClienteController" as CC
participant "Clientes: Cliente" as C
participant "ClienteEncontrado: Cliente" as CE
participant "CajaAhorro" as CA
participant "Prestamo: PrestamoPersonal" as P
participant "Operacion" as O

Cliente -> PC: solicitarPrestamoPersonal(SolicitarPrestamoDTO p): int
activate PC

PC -> CC: getCliente(int dni): Cliente
activate CC

loop Por cada cliente

    opt nroCliente coincide
        CC -> C: nroCliente(): int
        activate C
        CC <-- C: cliente
        deactivate C
    end

end

CC --> PC: cliente encontrado
deactivate CC

PC -> CE: getCaja(): CajaAhorro
activate CE
CE --> PC: caja de ahorro encontrada
deactivate CE

PC -> P: PrestamoPersonal (double monto, int plazo, double tasa, Cliente cliente)
activate P
PC <-- P: <<create>> prestamo Personal creado
deactivate P

PC -> CA: agregarSaldo(float saldo)
activate CA
CA --> PC: true
deactivate CA

PC -> O: <<create>> Operacion(Date fecha, TipoOperacion tipo, float monto)
activate O
O --> PC: Operacion registrada
deactivate O

PC -> CA : registrarOperacionCajaAhorro(Operacion operacion)
activate CA
CA --> PC: Operacion registrada en CajaAhorro
deactivate CA


PC --> Cliente: Prestamo confirmado
@enduml