@startuml
actor Cliente
participant "PrestamoController" as PC
participant "ClienteController" as CC
participant "Cliente" as C
participant "CajaAhorro" as CA

Cliente -> PC: altaPrestamoPersonal(PrestamoPersonalDTO dto)
activate PC

PC -> CC: buscarClientePorNro(dto.nroCliente)
activate CC

loop x cada cliente<listadoClientes>
    CC -> C: getNroCliente()
    activate C
    opt si nroCliente coincide
        CC <-- C: Cliente
    end
    deactivate C
end
deactivate CC

PC -> C: getCajaAhorro()
activate C
C --> PC: CajaAhorro
deactivate C

PC -> CA: acreditarDinero(dto.montoPrestado)
activate CA

PC -> CA: registrarOperacion(Operacion)
deactivate CA

PC --> Cliente: PrestamoPersonal
deactivate PC
@enduml